CREATE TYPE post_status AS ENUM ('Published', 'Draft', 'Scheduled')

CREATE TABLE posts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL, 
	content TEXT NOT NULL, 
	publication_date DATE NOT NULL, 
	status post_status DEFAULT 'Draft'::post_status NOT NULL, 
	likes INTEGER DEFAULT 0 NOT NULL, 
	comments INTEGER DEFAULT 0 NOT NULL, 
	engagement_rate REAL DEFAULT 0.0 NOT NULL, 
	media_urls TEXT[], 
	CONSTRAINT posts_pkey PRIMARY KEY (id)
)



CREATE TABLE pg_stat_statements_info (
	dealloc BIGINT, 
	stats_reset TIMESTAMP WITH TIME ZONE
)



CREATE TABLE pg_stat_statements (
	userid OID, 
	dbid OID, 
	toplevel BOOLEAN, 
	queryid BIGINT, 
	query TEXT, 
	plans BIGINT, 
	total_plan_time DOUBLE PRECISION, 
	min_plan_time DOUBLE PRECISION, 
	max_plan_time DOUBLE PRECISION, 
	mean_plan_time DOUBLE PRECISION, 
	stddev_plan_time DOUBLE PRECISION, 
	calls BIGINT, 
	total_exec_time DOUBLE PRECISION, 
	min_exec_time DOUBLE PRECISION, 
	max_exec_time DOUBLE PRECISION, 
	mean_exec_time DOUBLE PRECISION, 
	stddev_exec_time DOUBLE PRECISION, 
	rows BIGINT, 
	shared_blks_hit BIGINT, 
	shared_blks_read BIGINT, 
	shared_blks_dirtied BIGINT, 
	shared_blks_written BIGINT, 
	local_blks_hit BIGINT, 
	local_blks_read BIGINT, 
	local_blks_dirtied BIGINT, 
	local_blks_written BIGINT, 
	temp_blks_read BIGINT, 
	temp_blks_written BIGINT, 
	shared_blk_read_time DOUBLE PRECISION, 
	shared_blk_write_time DOUBLE PRECISION, 
	local_blk_read_time DOUBLE PRECISION, 
	local_blk_write_time DOUBLE PRECISION, 
	temp_blk_read_time DOUBLE PRECISION, 
	temp_blk_write_time DOUBLE PRECISION, 
	wal_records BIGINT, 
	wal_fpi BIGINT, 
	wal_bytes NUMERIC, 
	jit_functions BIGINT, 
	jit_generation_time DOUBLE PRECISION, 
	jit_inlining_count BIGINT, 
	jit_inlining_time DOUBLE PRECISION, 
	jit_optimization_count BIGINT, 
	jit_optimization_time DOUBLE PRECISION, 
	jit_emission_count BIGINT, 
	jit_emission_time DOUBLE PRECISION, 
	jit_deform_count BIGINT, 
	jit_deform_time DOUBLE PRECISION, 
	stats_since TIMESTAMP WITH TIME ZONE, 
	minmax_stats_since TIMESTAMP WITH TIME ZONE
)

